import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "..");
const privateMarkers = ["http://100.100.10.20:8787", "100.100.10.20", ":8787"];

function filesBelow(directory: string): string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory).flatMap((entry) => {
    const path = join(directory, entry);
    return statSync(path).isDirectory() ? filesBelow(path) : [path];
  });
}

test("private configuration modules are server-only and client components have no server imports", () => {
  const serverFiles = filesBelow(join(root, "src/server")).filter((path) => path.endsWith(".ts"));
  assert.ok(serverFiles.length > 0);
  for (const path of serverFiles) {
    const source = readFileSync(path, "utf8");
    assert.match(source, /^import "server-only";/, relative(root, path));
  }

  const appFiles = filesBelow(join(root, "src/app")).filter((path) => /\.tsx?$/.test(path));
  for (const path of appFiles) {
    const source = readFileSync(path, "utf8");
    if (source.startsWith('"use client"')) {
      assert.doesNotMatch(source, /(?:@\/server|process\.env|ELOVA_BACKEND_URL)/, relative(root, path));
    }
  }
});

test("the generated API client is committed and consumed instead of handwritten contract types", () => {
  const generatedTypes = readFileSync(resolve(root, "../../packages/api-client/src/generated/types.gen.ts"), "utf8");
  const healthClient = readFileSync(join(root, "src/server/backend-health.ts"), "utf8");
  assert.match(generatedTypes, /auto-generated by @hey-api\/openapi-ts/);
  assert.match(healthClient, /from "@elova\/api-client"/);
  assert.match(healthClient, /getReadiness/);
});

test("browser bundles, HTML, JSON artifacts, redirects, and source maps contain no private endpoint", () => {
  const nextDirectory = join(root, ".next");
  assert.ok(existsSync(nextDirectory), "run the web build before boundary tests");

  const browserFiles = filesBelow(join(nextDirectory, "static"));
  const renderedArtifacts = filesBelow(join(nextDirectory, "server/app"))
    .filter((path) => /\.(?:html|json|map|rsc|txt)$/.test(path));
  const sourceMaps = filesBelow(nextDirectory).filter((path) => path.endsWith(".map"));
  const candidates = [...new Set([...browserFiles, ...renderedArtifacts, ...sourceMaps])];

  assert.ok(candidates.length > 0, "expected browser build artifacts");
  for (const path of candidates) {
    const contents = readFileSync(path, "utf8");
    for (const marker of privateMarkers) {
      assert.equal(contents.includes(marker), false, `${relative(root, path)} leaked ${marker}`);
    }
  }
});

test("no public environment variable alias exists for the backend", () => {
  const ownedSource = [
    ...filesBelow(join(root, "src")),
    ...filesBelow(resolve(root, "../../packages/api-client/src")),
  ].filter((path) => /\.(?:ts|tsx|js|json)$/.test(path));

  for (const path of ownedSource) {
    assert.doesNotMatch(readFileSync(path, "utf8"), /NEXT_PUBLIC_[A-Z0-9_]*(?:BACKEND|GX10|PRIVATE)/);
  }
});
